version: '3.5'

services:
    nginx:
        image: articles_api_nginx:latest
        build:
            context: ./docker/
            args:
                BUILD_ARGUMENT_ENV: dev
            dockerfile: ./nginx/Dockerfile
        container_name: articles_api_nginx
        restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - .:/var/www/html:ro,cached
        depends_on:
            - symfony
        networks:
            - symfony

    symfony: &symfony-template
        image: articles_api_symfony:latest
        build:
            context: .
            args:
                BUILD_ARGUMENT_ENV: dev
                HOST_UID: ${HOST_UID}
                HOST_GID: ${HOST_GID}
            dockerfile: ./Dockerfile
        container_name: articles_api_symfony
        volumes:
            - .:/var/www/html:cached
        depends_on:
            - mysql
        networks:
            - symfony

    mysql:
        image: mysql:8.0
        container_name: articles_api_mysql
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: symfony
        ports:
            - "33061:3306"
        volumes:
            - ./var/mysql-data:/var/lib/mysql:delegated
        networks:
            - symfony

networks:
    symfony:
        name: symfony
